FROM tiangolo/node-frontend:10 as build-stage

# Working Directory
WORKDIR /app

# Copy source code to working directory
COPY . package*.json /app/

RUN npm install

COPY ./ /app/

ARG configuration=production

# Install packages from requirements.txt
# hadolint ignore=DL3013
RUN npm run build -- --output-path=./dist/out --configuration $configuration



FROM nginx:1.15

COPY --from=build-stage /app/dist/out/ /usr/share/nginx/html

COPY --from=build-stage /nginx.conf /etc/nginx/conf.d/default.conf
## Step 4:
# Expose port 80
EXPOSE  80


